# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 296e393b298691f523308c09608e892a945d538fbefc15bd259cc375ea4c46395882ca341442b78494c0933a91f1961a3d603107b1a3dbeda2cdaa195f8d43bf

test:
  secret_key_base: e5dad7eb0f16d3af4741777f448a6389f715cc4231c9ad3898fd7e3150350ee2574196cbda8d105b5793d2224043f1618d5b4571c7821f1c32780c46b159edd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
